---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: demo
  labels:
    app: website
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: demo
  labels:
    app: website
spec:
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: thecloudgarage/apache-docker-example:v1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 80
